---
- name: Create directories for Jenkins
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes
  with_items:
    - '/var/cache/jenkins/tmp'
    - '/var/cache/jenkins/heapdumps'
    - '/var/lib/jenkins/plugins'


- name: Create directories for Jenkins
  file:
    path: "/var/lib/jenkins/jobs/test_init_proj"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes