---

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes

- name: Enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes

- name: Update JENKINS_JAVA_OPTIONS
  lineinfile:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: ".*-Djava.awt.headless=true.*"
    line: | 
      'JENKINS_JAVA_OPTIONS="
      -Djava.awt.headless=true 
      -Djava.net.preferIPv4Stack=true 
      -Djenkins.install.runSetupWizard=false 
      -Djava.io.tmpdir=/var/cache/jenkins/tmp/ 
      -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York 
      -Duser.timezone=America/New_York"'
    state: present

- name: Update JENKINS_ARGS
  lineinfile:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: ".*JENKINS_ARGS=.*"
    line: 'JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins"'
    state: present

- name: download jenkins-plugin-manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.14/jenkins-plugin-manager-2.12.14.jar
    dest: $HOME/jenkins-plugin-manager.jar

- name: Copy the plugins.yaml file
  copy:
    dest: "$HOME/plugins.yaml"
    src: "../files/plugins.yaml"

- name: Copy the jenkins.yaml file
  copy:
    dest: "/var/lib/jenkins/jenkins.yaml"
    src: "../files/jenkins.yaml"


- name: run the jenkins-plugin-manager
  command: java -jar /root/jenkins-plugin-manager.jar --jenkins-version 2.426.3 --plugin-file $HOME/plugins.yaml --plugin-download-directory /var/lib/jenkins/plugins

- name: update JENKINS_HOME ownership
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    state: directory
    recurse: yes