---
- name: download jenkins-plugin-manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.14/jenkins-plugin-manager-2.12.14.jar
    dest: $HOME/jenkins-plugin-manager.jar

- name: Copy the plugins.yaml file
  copy:
    dest: "$HOME/plugins.yaml"
    src: "../files/plugins.yaml"

- name: Copy the jenkins.yaml file
  copy:
    dest: "/var/lib/jenkins/jenkins.yaml"
    src: "../files/jenkins.yaml"


- name: run the jenkins-plugin-manager
  command: java -jar /root/jenkins-plugin-manager.jar --jenkins-version 2.426.3 --plugin-file $HOME/plugins.yaml --plugin-download-directory /var/lib/jenkins/plugins
