---
- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes

- name: Enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes

- name: Update JENKINS_JAVA_OPTIONS
  lineinfile:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: ".*-Djava.awt.headless=true.*"
    line: | 
      'JENKINS_JAVA_OPTIONS="
      -Djava.awt.headless=true 
      -Djava.net.preferIPv4Stack=true 
      -Djenkins.install.runSetupWizard=false 
      -Djava.io.tmpdir=/var/cache/jenkins/tmp/ 
      -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York 
      -Duser.timezone=America/New_York"'
    state: present

- name: Update JENKINS_ARGS
  lineinfile:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: ".*JENKINS_ARGS=.*"
    line: 'JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins"'
    state: present

