---
- name: Open port 8080/tcp (permanent)
  firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    state: enabled
  become: yes

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
