---
- name: Cat initialAdminPassword
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password
  ignore_errors: true

- name: Print initialAdminPassword
  debug:
    var: initial_admin_password.stdout_lines
  ignore_errors: true
