---
- name: Download Jenkins repository file
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Create jenkins user
  user:
    name: jenkins
    password: "{{ 'jenkins' | password_hash('sha512') }}"
    state: present

- name: Create directories for Jenkins
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes
  with_items:
    - '/var/cache/jenkins/tmp'
    - '/var/cache/jenkins/heapdumps'
    - '/var/lib/jenkins/plugins'

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes

- name: Enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes

- name: Update JENKINS_JAVA_OPTIONS
  lineinfile:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: ".*-Djava.awt.headless=true.*"
    line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djenkins.install.runSetupWizard=false -Djava.io.tmpdir=/var/cache/jenkins/tmp/ -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York -Duser.timezone=America/New_York"'
    state: present

- name: Update JENKINS_ARGS
  lineinfile:
    path: "/usr/lib/systemd/system/jenkins.service"
    regexp: ".*JENKINS_ARGS=.*"
    line: 'JENKINS_ARGS="--pluginroot=/var/cache/jenkins/plugins"'
    state: present

# - name: Start Jenkins service
#   systemd:
#     name: jenkins
#     state: started

# - name: Check Jenkins service status
#   shell: "systemctl status jenkins.service | grep Active:"
#   register: jenkins_status_output

# - name: Display Jenkins service status
#   debug:
#     var: jenkins_status_output.stdout_lines

- name: download jenkins-plugin-manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.14/jenkins-plugin-manager-2.12.14.jar
    dest: $HOME/jenkins-plugin-manager.jar

- name: Copy the plugins.yaml file
  copy:
    dest: "$HOME/plugins.yaml"
    src: "../templates/plugins.yaml"

- name: Copy the jenkins.yaml file
  copy:
    dest: "/var/lib/jenkins/jenkins.yaml"
    src: "../templates/jenkins.yaml"

# - name: Copy the init files
#   copy:
#     dest: "/var/lib/jenkins/init.groovy.d/"
#     src: "init.groovy.d/"

- name: run the jenkins-plugin-manager
  command: java -jar /root/jenkins-plugin-manager.jar --jenkins-version 2.426.3 --plugin-file $HOME/plugins.yaml --plugin-download-directory /var/lib/jenkins/plugins

- name: update JENKINS_HOME ownership
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    state: directory
    recurse: yes







- name: Create directories for Jenkins
  file:
    path: "/var/lib/jenkins/jobs/test_init_proj"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes
- name: copy job
  copy:
    dest: "/var/lib/jenkins/jobs/test_init_proj/config.xml"
    src: "../templates/job1.xml"

# - name: restart jenkins service
#   systemd:
#     name: jenkins
#     state: restarted


- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started

- name: Check Jenkins service status
  shell: "systemctl status jenkins.service | grep Active:"
  register: jenkins_status_output

- name: Display Jenkins service status
  debug:
    var: jenkins_status_output.stdout_lines

- name: Cat initialAdminPassword
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password

- name: Print initialAdminPassword
  debug:
    var: initial_admin_password.stdout_lines